name: Trigger auto deployment for medofficehq-backend-production

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/medofficehq-backend-production-AutoDeployTrigger-9a0559e3-43e4-44bf-b512-d10800405346.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MEDOFFICEHQBACKENDPRODUCTION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEDOFFICEHQBACKENDPRODUCTION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEDOFFICEHQBACKENDPRODUCTION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile

          registryUrl: aivoiceagent.azurecr.io
          registryUsername: ${{ secrets.MEDOFFICEHQBACKENDPRODUCTION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEDOFFICEHQBACKENDPRODUCTION_REGISTRY_PASSWORD }}

          containerAppName: medofficehq-backend-production
          resourceGroup: medofficehq-resource
          imageToBuild: aivoiceagent.azurecr.io/medofficehq-backend-production:${{ github.sha }}

          # REQUIRED for deployment
          targetPort: 8000
          ingress: external
